environment:
  nodejs_version: "12"

version: 1.2.{build}

install:
  - sh: Install-Product node $env:nodejs_version
  - sh: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - sh: node --version
  - sh: npm install

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - develop
build:
  verbosity: minimal