import "lib-utils-ts/src/globalUtils";
import { properties } from "lib-utils-ts/src/Interface";
import { filterLogLevel, IPropertiesFileA, Loggable, Pipe, strLogLevel } from "./Loggable";
import { Loader } from "./Loader";
export declare abstract class AbsLogger implements Loggable {
    static readonly DEFAULT_LOG_PATTERN_MONO: string;
    static readonly WEBDRIVER_LOG_PATTERN_COLORED: string;
    static readonly EXPRESS_MIDDLEWARE_PATTERN: string;
    static readonly STATS_MEMORY_PATTERN: string;
    static readonly CPU_USAGE_PATTERN: string;
    static readonly VERSION_USAGE_PATTERN: string;
    private static readonly COLORS_REGEXP;
    protected static parser: String;
    protected static outputLog: string;
    protected static saveLog: boolean;
    protected static logStdout: boolean;
    protected static logLevel: filterLogLevel<strLogLevel>;
    protected static colorize: boolean;
    protected static cleanUpBeforeSave: boolean;
    protected static logRotate: string;
    protected static rotateOutOfTimestamp: Date;
    static oid: String;
    protected static pipeStdout: Pipe<string>;
    protected static propertiesConfig: properties<Object> | IPropertiesFileA;
    protected static fileNamePattern: String;
    protected static logfileReuse: String;
    protected static fileMaxSize: number;
    protected prop: Object;
    protected name: String;
    protected pattern: String;
    protected constructor(name?: String);
    warn(...args: any[]): void;
    log(...args: any[]): void;
    info(...args: any[]): void;
    debug(...args: any[]): void;
    error(...args: any[]): void;
    custom(...args: any[]): void;
    setPattern(pattern?: String): Loggable;
    setProp(key: string | number, value: any): Loggable;
    setPropObject(...args: Object[]): Loggable;
    static setPropertiesConfigHandle(handle?: properties<Object> | IPropertiesFileA): void;
    static setPropertiesFile(path: string, json?: boolean): void;
    protected static reloadConfiguration(): void;
    static setOutputLog(path?: string): void;
    static setSaveLog(save?: boolean): void;
    static setLogStdout(stdout?: boolean): void;
    static setParser(parsing?: String): void;
    static setPattern(pattern?: String): void;
    static level(level?: filterLogLevel<strLogLevel>): void;
    static popLevel(logType?: strLogLevel): void;
    static pushLevel(logType?: strLogLevel): void;
    static setLogFilePattern(pattern?: String): void;
    static setFileMaxSize(bytes?: number): void;
    static setLogFileReuse(path?: String): void;
    static setPipeStdout(pipe?: Pipe<string>): void;
    static setColorize(status?: boolean): void;
    static setCleanUpBeforeSave(state?: boolean): void;
    static setLogRotate(rotate?: string): void;
    protected static restartRotate(): void;
    protected static translateColorToInt(color?: string): String;
    static getLoggerFileName(): String;
    protected static colorizeString(message?: string, type?: string, colorize?: boolean): string;
    protected static parseString(message?: String, type?: string, name?: string, dat?: Object): String;
    protected static stdout(): void;
}
export declare class Logger extends AbsLogger {
    constructor(name?: String);
    static expressRouteLoggerMiddleware(pattern?: string): Function;
    static getLoader(sizeOf?: number): Loader;
    static stats(): Stats;
    static factory(name?: String): Logger;
}
declare class Stats {
    private static readonly INSTANCE;
    private readonly Log;
    private readonly patternList;
    constructor();
    private apply;
    memory(pattern?: string): void;
    cpu(pattern?: string): void;
    version(pattern?: string): void;
    static getInstance(): Stats;
}
export {};
